name: lut  # Change to your preferred environment name
channels:
  - conda-forge
dependencies:
  - python=3.14
  - cerberus
  - gitpython
  - joblib
  - netcdf4
  - numpy
  - pytest
  - python-cdo
  - pyyaml
  - xarray
