# Input Parameters

region : "NorthAmerica"
forward : False
backgrd : True
mcgrath : False
addtree : False
mcgback : False
irri : False

syear : 2015
eyear : 1950
npfts : 16
esayear : 2015
xsize : 95
ysize : 89
gradef : 9
crodef : 13
shrdef : 8

oname : "LUCAS_LUC7_ESACCI_LUH2"
lcd : "ESACCI-LC-L4-LCCS-Map-300m-P1Y" # version of ESA-file
mcg : "combined_species_mtc" # name of McGrath file
vers : "v2.0.7"
res : 100 # resolution in 10th of a degree
remap : "bilinear"
scenario : "historical"

trans : True
state : False
