# Input Parameters

# LUT configuration
region : "Germany"
forward : True # forward or backward simulation
backgrd : True # background  
mcgrath : False # mcgrath
addtree : True # addtree
mcgback : False # mcgback
irri : True # irrigation
syear : 2015 # start year
eyear : 2100 # end year
npfts : 16 # number of PFTs
esayear : 2015
mcgrath_eyear : 2100 # end year of mcgrath file (in case that its different from eyear)
xsize : 95 # xsize of the region
ysize : 91 # ysize of the region
remap : "bilinear" # remapping method
scenario : "rcp26" # scenario
grid : 0.1 # resolution in degrees

# LUH2 prepare data configuration
prepare_luh2_data: False # prepare LUH2 data
prepare_mcgrath: False # prepare mcgrath data

# Plot configuration
plot : True
plot_npft: null # if not plot_npft is given, all npfts are plotted 
plot_year: 70 # if not plot_year is given, first year is plotted
