# Input Parameters

region : "Germany"
forward : False
backgrd : True
mcgrath : False
addtree : False
mcgback : False
irri : False
prepare_luh2_data: False
prepare_mcgrath: False

syear : 1950
eyear : 2015
npfts : 16
esayear : 2015
mcgrath_eyear : 2010
xsize : 95
ysize : 91
gradef : 9
crodef : 13
shrdef : 8

oname : "LUCAS_LUC7_ESACCI_LUH2"
lcd : "ESACCI-LC-L4-LCCS-Map-300m-P1Y" # version of ESA-file
mcg : "combined_species_mtc" # name of McGrath file
vers : "v2.0.7"
res : 100 # resolution in 10th of a degree
remap : "bilinear"
scenario : "historical"

trans : True
state : True

# Plot configuration
plot : True
# if not plot_npft is given, all npfts are plotted
plot_npft: null 
# if not plot_year is given, first year is plotted
plot_year: 0